export const ALL_USERLISTS_REQUEST = 'ALL_USERLIST_REQUEST'
export const ALL_USERLISTS_SUCCESS = 'ALL_USERLIST_SUCCESS'
export const ALL_USERLISTS_FAIL = 'ALL_USERLIST_FAIL'

export const USERLIST_DETAILS_REQUEST = 'USERLIST_DETAILS_REQUEST'
export const USERLIST_DETAILS_SUCCESS = 'USERLIST_DETAILS_SUCCESS'
export const USERLIST_DETAILS_FAIL = 'USERLIST_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

 
